# 本地加密端配置文件


# 总在线矿机总数量限制
workers_limit: 1000
workers_limit_port: 1000    # 每个端口限制多少台矿机

real_latency: false    # 等矿池回应才发给矿机, 默认为 flase, 这一行参数可以删除


monitor_config: true    # 监控此配置文件, 下面的端口信息更改,增加或删除或更改, 则更换过来
monitor_port: true      # 监控端口异常退出, 异常退出则尝试重复开



servers:
  - name: 本地端加密 - 鱼池btc - 本地端的写法
    encrypt: true        # 是否使用加密, 本地端表示加密, 服务端表示解密,
    ip: 0.0.0.0:14881    # 给本地的btc接进来的端口, 矿机通过这个端口连接这台加密机
    pool:
      ip: 8.218.238.31:14881       # 发给自己的服务端解密








