# 已完成  iron  kas    cfx   rxd   dnx
# 未完成  etc  rvn


# 总在线矿机总数量限制
workers_limit: 500
workers_limit_port: 100    # 每个端口限制多少台矿机


# 证书, 亦可不提供使用默认的, 自己提供也行
cert: cert.pem
key: key.pem



servers:
  - name: IRON抽水
    ip: 0.0.0.0:12907     # 给客人连接的端口, 一般前面固定为0.0.0.0
    ssl: true             # 给客人连接, 一般要开ssl
    coin: IRON            # 币种, 参数上面完成的
    pool: # 实际代理矿池
      ip: hk.ironfish.herominers.com:1145
      ssl: false
      proxy: ""              # 如果安装在国内, 则这里要填上socks5代理
    devfee: # 可开多个抽水, 损耗会更大
      - name: "小王"
        worker_name: "devfee-1"
        fee_percent: 3     # 3%
        address: "your wallet address"  #
        pool:          # 跨池抽就要填, 不填表示跟主池一样
          ip: hk.ironfish.herominers.com:1145       #  这里填抽到哪个池
          ssl: false
          proxy: ""

  - name: RXD抽水
    ip: 0.0.0.0:12908     # 给客人连接的端口, 一般前面固定为0.0.0.0
    ssl: true
    coin: RXD            # 币种, 参数上面完成的
    pool: # 实际代理矿池
      ip: hk.ironfish.herominers.com:1145
      ssl: false
      proxy: ""              # 如果安装在国内, 则这里要填上socks5代理
    devfee: # 可开多个抽水, 损耗会更大
      - name: 同学
        worker_name: "devfee-1"
        fee_percent: 1     # 3%
        address: "your wallet address"  #
        pool:          # 跨池抽就要填, 不填表示跟主池一样
          ip: hk.ironfish.herominers.com:1145       #  这里填抽到哪个池
          ssl: false
          proxy: ""
      - name: 同事
        worker_name: "devfee-2"
        fee_percent: 3     # 3%
        address: "your wallet address"  #
        pool:          # 跨池抽就要填, 不填表示跟主池一样
          ip: hk.ironfish.herominers.com:1145       #  这里填抽到哪个池
          ssl: false
          proxy: ""


  - name: KAS自用
    ip: 0.0.0.0:12906
    ssl: true
    coin: KAS
    pool: # 实际代理矿池
      ip: kas-asia.f2pool.com:1400
      ssl: false
      proxy: ""




