# 已完成  iron  kas    cfx   rxd   dnx
# 未完成  etc  rvn


# 总在线矿机总数量限制
workers_limit: 500
workers_limit_port: 100    # 每个端口限制多少台矿机


# 证书, 亦可不提供使用默认的, 自己提供也行
cert: cert.pem
key: key.pem



servers:
  - name: IRON抽水
    ip: 0.0.0.0:17650     # 给客人连接的端口, 一般前面固定为0.0.0.0
    ssl: true             # 给客人连接, 一般要开ssl
    coin: IRON            # 币种, 参数上面完成的
    pool: # 实际代理矿池
      ip: hk.ironfish.herominers.com:1145
      ssl: false
      proxy: ""              # 如果安装在国内, 则这里要填上socks5代理
    devfee: # 可开多个抽水, 损耗会更大
      - name: "小王"
        worker_name: "devfee-1"
        fee_percent: 3     # 3%
        address: "7d878a6b6fb8cdaa32b334091e3fee5483eb9e7c3933b386e2bf4a1bf44dc36a"  #  改成你自己的钱包
        pool:          # 跨池抽就要填, 不填表示跟主池一样
          ip: hk.ironfish.herominers.com:1145       #  这里填抽到哪个池
          ssl: false
          proxy: ""

  - name: RXD抽水
    ip: 0.0.0.0:10160     # 给客人连接的端口, 一般前面固定为0.0.0.0
    ssl: true
    coin: RXD            # 币种, 参数上面完成的
    pool: # 实际代理矿池
      ip: pool.sg.woolypooly.com:3122
      ssl: false
      proxy: ""              # 如果安装在国内, 则这里要填上socks5代理
    devfee: # 可开多个抽水, 损耗会更大
      - name: 同学
        worker_name: "devfee-1"
        fee_percent: 1     # 1%
        address: "1KFFbumRuJhyWSTZNRPEPy1DjDj5rKnSJD"  # 改成你自己的钱包
        pool:          # 跨池抽就要填, 不填表示跟主池一样
          ip: pool.sg.woolypooly.com:3122       #  这里填抽到哪个池
          ssl: false
          proxy: ""
      - name: 同事
        worker_name: "devfee-2"
        fee_percent: 3     # 3%
        address: "1KFFbumRuJhyWSTZNRPEPy1DjDj5rKnSJD"  # 改成你自己的钱包
        pool:          # 跨池抽就要填, 不填表示跟主池一样
          ip: pool.sg.woolypooly.com:3122       #  这里填抽到哪个池
          ssl: false
          proxy: ""


  - name: CFX抽水
    ip: 0.0.0.0:13000     # 给客人连接的端口, 一般前面固定为0.0.0.0
    ssl: true
    coin: CFX            # 币种, 参数上面完成的
    pool: # 实际代理矿池
      ip: pool.sg.woolypooly.com:3094
      ssl: false
      proxy: ""              # 如果安装在国内, 则这里要填上socks5代理
    devfee: # 可开多个抽水, 损耗会更大
      - name: 同学
        worker_name: "devfee-1"
        fee_percent: 1     # 1%
        address: "cfx:aapryhjwgd9be25dku6c9sjwv89kr5je1ukshb54py"  # 改成你自己的钱包
        pool:          # 跨池抽就要填, 不填表示跟主池一样
          ip: pool.sg.woolypooly.com:3094       #  这里填抽到哪个池
          ssl: false
          proxy: ""

  - name: DNX抽水
    ip: 0.0.0.0:10615     # 给客人连接的端口, 一般前面固定为0.0.0.0
    ssl: false
    coin: DNX            # 币种, 参数上面完成的
    pool: # 实际代理矿池
      ip: dnx.sg.ekapool.com:19666
      ssl: false
      proxy: ""              # 如果安装在国内, 则这里要填上socks5代理
    devfee: # 可开多个抽水, 损耗会更大
      - name: 同学
        worker_name: "devfee-1"
        fee_percent: 1     # 1%
        address: "XwnaXVqNeC1MVPZYEzCzzAQLiFzsGZ7aei8d6TCD1kyp7qzfHnJNxRvTDgnM4X3qjsZrgfgojbnGEZRVepMAQYce28bekk9Xk"  # 改成你自己的钱包



  - name: KAS自用
    ip: 0.0.0.0:16510
    ssl: true
    coin: KAS
    pool: # 实际代理矿池
      ip: pool.sg.woolypooly.com:3112
      ssl: false
      proxy: ""




